# Generated by Django 2.1.4 on 2018-12-17 15:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=256)),
                ('blog_body', models.TextField()),
                ('blog_create_time', models.DateTimeField(default=datetime.datetime(2018, 12, 17, 15, 38, 7, 694574, tzinfo=utc))),
                ('blog_update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-blog_create_time',),
            },
        ),
    ]
