# Generated by Django 2.1.4 on 2018-12-21 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0002_auto_20181217_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_videoname',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 6, 53, 51, 595848, tzinfo=utc)),
        ),
    ]
